const types = {
    SET_MAIN_MENUS: 'SET_MAIN_MENUS',
    SET_OTHER_MENUS: 'SET_OTHER_MENUS',
    SET_COMPLETED_TAB: 'SET_COMPLETED_TAB',
    SET_SELECTED_MENU: 'SET_SELECTED_MENU',
    SET_DISCOUNT_SELECT: "SET_DISCOUNT_SELECT",
    SET_SELECTED_DISCOUNT_MENU: "SET_SELECTED_DISCOUNT_MENU",
    ADD_SELECTED_ITEM: 'ADD_SELECTED_ITEM',
    REMOVE_SELECTED_ITEM: "REMOVE_SELECTED_ITEM",
    EMPTY_SELECTED_ITEM: "EMPTY_SELECTED_ITEM",
    OPEN_TOAST: "OPEN_TOAST",
    CLOSE_TOAST: "CLOSE_TOAST",
    SET_LAST_LOCATION: "SET_LAST_LOCATION",

}
export default types
